name: wallet_sdk
author: Fuse Network <hello@fuse.io>
version: 0.2.4+23
homepage: https://github.com/fuseio/wallet_core
description: Fuse wallet core Dart library to interact with Ethereum based networks and APIs.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  build_runner: ^2.0.5
  get_it: ^7.1.4
  mockito: ^5.0.10
  test: ^1.17.9
  web3dart: ^2.1.4
